### ISSUE TITLE
Readme is incorrect

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cinq-auditor-domain-hijacking#6]
The readme for this module isnt from this module

**Comment by markofu** [comment]
Fixed in #7 . Look ok @tomvachon ?

**Comment by tomvachon** [comment]
No, it doesnt.  the description on on one is wrong, or reads wrong: "JSON document with roles to push to accounts. See documentation for examples"

**Comment by bunjiboys** [comment]
Was fixed a while back
